# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ITISRequest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'SDWebImage'


  # Pods for ITISRequest

  target 'ITISRequestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ITISRequestUITests' do
    # Pods for testing
  end
end
